### ISSUE TITLE
Get the Tileset image

### ISSUE THREAD

**Issue by toastal** [Osmose/phaser-tiled-json-external-loader#1]
In the tileset.json file, there's a property, `image`, with a string to a `.png`. Why stop at the tileset? Can this plugin go the rest of the way and add this to the cache as well?

**Comment by Osmose** [comment]
Thanks for the issue!

The tilemap/set creator methods still expect to be given a key to the image asset for each tileset, and it's not clear what key we would use in the cache for each tileset image if we auto-loaded them. I dunno how we would handle conflicting keys between tilemaps either. 

I'd rather not break the pattern of loading and supplying images separately, since the API is more strict about relying on that (vs external tilemaps, which don't affect the tilemap creator API at all).
