### ISSUE TITLE
Is it possible to use regular Phaser 3 plugin loader?

### ISSUE THREAD

**Issue by blopa** [Osmose/phaser-tiled-json-external-loader#3]
First of all, thanks for sharing this super useful plugin!

I have just one question: Is it possible to use this plugin via the regular Phaser 3 plugin loader? If not possible, can you make it compatible?

https://rexrainbow.github.io/phaser3-rex-notes/docs/site/loader/#plugin

Thanks

**Comment by Osmose** [comment]
I'm rusty on Phaser so I'm not 100% certain, but I think the way this works is not compatible with the plugin framework, because you need to be able to use this during the preload step, which is when you'd call that load function, and there's no (reasonable) way to say "load this plugin and delay doing anything else in the preload step until it's running".

The only benefit I can see of being compatible with the plugin loader would be including loading this plugin in a loading bar for your game, but really you should be bundling / including this code with the initial Phaser code before you start loading assets anyway. Plus, the filesize is small enough compared to assets that it shouldn't really affect the loading bar much.

If I'm wrong and you end up finding a way to make it work, feel free to open a pull request. Thanks for the issue!
